from enum import StrEnum


class ProjectStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class ProjectType(StrEnum):
    DFG_INTERNAL = "DFG_INTERNAL"
    CLIENT = "CLIENT"
    R_AND_D = "R_AND_D"


class RepositoryAdapterType(StrEnum):
    LOCAL_GIT = "LOCAL_GIT"


class RepositoryAccessMode(StrEnum):
    READ_ONLY = "READ_ONLY"


class AuthorityLevel(StrEnum):
    L0 = "L0"
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"


class TaskComplexity(StrEnum):
    T0 = "T0"
    T1 = "T1"
    T2 = "T2"
    T3 = "T3"
    T4 = "T4"


class TaskPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    BLOCKED = "BLOCKED"
    IMPLEMENTATION_COMPLETE = "IMPLEMENTATION_COMPLETE"
    DOCUMENTATION_PENDING = "DOCUMENTATION_PENDING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AcceptanceCriterionStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_EVALUATED = "NOT_EVALUATED"


class AllowedAction(StrEnum):
    READ_REPOSITORY = "READ_REPOSITORY"
    READ_DOCUMENTATION = "READ_DOCUMENTATION"
    RUN_TESTS = "RUN_TESTS"
    CREATE_TEMP_FILES = "CREATE_TEMP_FILES"
    WRITE_SOURCE = "WRITE_SOURCE"
    WRITE_TESTS = "WRITE_TESTS"
    WRITE_DOCUMENTATION = "WRITE_DOCUMENTATION"
    CREATE_MIGRATION = "CREATE_MIGRATION"
    CREATE_COMMIT = "CREATE_COMMIT"


class BlockerCode(StrEnum):
    MISSING_REPOSITORY = "MISSING_REPOSITORY"
    INVALID_CONTRACT = "INVALID_CONTRACT"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    AUTHORITY_INSUFFICIENT = "AUTHORITY_INSUFFICIENT"
    WORKSPACE_INVALID = "WORKSPACE_INVALID"
    REPOSITORY_STATE_UNSAFE = "REPOSITORY_STATE_UNSAFE"
    DECISION_REQUIRED = "DECISION_REQUIRED"
    DOCUMENTATION_REQUIRED = "DOCUMENTATION_REQUIRED"
    PROJECT_INACTIVE = "PROJECT_INACTIVE"


class TaskRunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class Actor(StrEnum):
    HUMAN = "HUMAN"
    CHATGPT = "CHATGPT"
    CODEX = "CODEX"
    LUCIUS = "LUCIUS"
    EXTERNAL_ENGINEERING_AGENT = "EXTERNAL_ENGINEERING_AGENT"
    SYSTEM = "SYSTEM"


class Environment(StrEnum):
    SANDBOX = "SANDBOX"
    DEVELOPMENT = "DEVELOPMENT"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"


class KnowledgeScope(StrEnum):
    GLOBAL = "GLOBAL"
    DFG = "DFG"
    DOMAIN = "DOMAIN"
    PROJECT = "PROJECT"
    CLIENT = "CLIENT"
    SESSION = "SESSION"


class ValidationStatus(StrEnum):
    OBSERVED = "OBSERVED"
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    CONTRADICTED = "CONTRADICTED"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"


class DetectionStatus(StrEnum):
    DETECTED = "DETECTED"
    INFERRED = "INFERRED"
    UNKNOWN = "UNKNOWN"


class SnapshotMode(StrEnum):
    FAST = "FAST"
    STANDARD = "STANDARD"
    DEEP = "DEEP"
