from enum import StrEnum


class ProjectStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class ProjectType(StrEnum):
    DFG_INTERNAL = "DFG_INTERNAL"
    CLIENT = "CLIENT"
    R_AND_D = "R_AND_D"


class RepositoryAdapterType(StrEnum):
    LOCAL_GIT = "LOCAL_GIT"


class RepositoryAccessMode(StrEnum):
    READ_ONLY = "READ_ONLY"


class AuthorityLevel(StrEnum):
    L0 = "L0"
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"


class TaskComplexity(StrEnum):
    T0 = "T0"
    T1 = "T1"
    T2 = "T2"
    T3 = "T3"
    T4 = "T4"


class TaskPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    BLOCKED = "BLOCKED"
    IMPLEMENTATION_COMPLETE = "IMPLEMENTATION_COMPLETE"
    DOCUMENTATION_PENDING = "DOCUMENTATION_PENDING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AcceptanceCriterionStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_EVALUATED = "NOT_EVALUATED"


class AllowedAction(StrEnum):
    READ_REPOSITORY = "READ_REPOSITORY"
    READ_DOCUMENTATION = "READ_DOCUMENTATION"
    RUN_TESTS = "RUN_TESTS"
    CREATE_TEMP_FILES = "CREATE_TEMP_FILES"
    WRITE_SOURCE = "WRITE_SOURCE"
    WRITE_TESTS = "WRITE_TESTS"
    WRITE_DOCUMENTATION = "WRITE_DOCUMENTATION"
    CREATE_MIGRATION = "CREATE_MIGRATION"
    CREATE_COMMIT = "CREATE_COMMIT"


class BlockerCode(StrEnum):
    MISSING_REPOSITORY = "MISSING_REPOSITORY"
    INVALID_CONTRACT = "INVALID_CONTRACT"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    AUTHORITY_INSUFFICIENT = "AUTHORITY_INSUFFICIENT"
    WORKSPACE_INVALID = "WORKSPACE_INVALID"
    REPOSITORY_STATE_UNSAFE = "REPOSITORY_STATE_UNSAFE"
    DECISION_REQUIRED = "DECISION_REQUIRED"
    DOCUMENTATION_REQUIRED = "DOCUMENTATION_REQUIRED"
    PROJECT_INACTIVE = "PROJECT_INACTIVE"


class TaskRunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class Actor(StrEnum):
    HUMAN = "HUMAN"
    CHATGPT = "CHATGPT"
    CODEX = "CODEX"
    LUCIUS = "LUCIUS"
    EXTERNAL_ENGINEERING_AGENT = "EXTERNAL_ENGINEERING_AGENT"
    SYSTEM = "SYSTEM"


class SourceType(StrEnum):
    CODE = "CODE"
    DOCUMENTATION = "DOCUMENTATION"
    TEST = "TEST"
    CONFIG = "CONFIG"
    GIT = "GIT"
    MEMORY = "MEMORY"
    EXTERNAL = "EXTERNAL"


class EvidenceStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    MISSING = "MISSING"


class RetrievalWarningCode(StrEnum):
    NO_RELEVANT_EVIDENCE = "NO_RELEVANT_EVIDENCE"
    CONTEXT_BUDGET_REACHED = "CONTEXT_BUDGET_REACHED"
    SOURCE_SKIPPED_BINARY = "SOURCE_SKIPPED_BINARY"
    SOURCE_SKIPPED_LARGE = "SOURCE_SKIPPED_LARGE"
    SOURCE_SKIPPED_SENSITIVE = "SOURCE_SKIPPED_SENSITIVE"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    SOURCE_MISSING = "SOURCE_MISSING"
    REPOSITORY_DIRTY = "REPOSITORY_DIRTY"


class MemoryType(StrEnum):
    SEMANTIC = "SEMANTIC"
    EPISODIC = "EPISODIC"
    PROCEDURAL = "PROCEDURAL"
    EVALUATIVE = "EVALUATIVE"
    PROJECT = "PROJECT"


class MemorySourceType(StrEnum):
    EVIDENCE_REFERENCE = "EVIDENCE_REFERENCE"
    TASK_RUN = "TASK_RUN"
    PROJECT_DOCUMENTATION = "PROJECT_DOCUMENTATION"
    AUDIT_EVENT = "AUDIT_EVENT"
    HUMAN_CORRECTION = "HUMAN_CORRECTION"
    FAILURE_EXPERIENCE = "FAILURE_EXPERIENCE"


class LearningCandidateType(StrEnum):
    PATTERN = "PATTERN"
    FAILURE_PATTERN = "FAILURE_PATTERN"
    PROCEDURE = "PROCEDURE"
    KNOWLEDGE_CORRECTION = "KNOWLEDGE_CORRECTION"
    OPTIMIZATION = "OPTIMIZATION"


class LearningCandidateStatus(StrEnum):
    PENDING = "PENDING"
    NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class KnowledgeFirewallClassification(StrEnum):
    PRIVATE = "PRIVATE"
    ABSTRACTABLE = "ABSTRACTABLE"
    GLOBAL_SAFE = "GLOBAL_SAFE"


class SanitizationStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    SANITIZED = "SANITIZED"
    REJECTED = "REJECTED"


class Environment(StrEnum):
    SANDBOX = "SANDBOX"
    DEVELOPMENT = "DEVELOPMENT"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"


class KnowledgeScope(StrEnum):
    GLOBAL = "GLOBAL"
    DFG = "DFG"
    DOMAIN = "DOMAIN"
    PROJECT = "PROJECT"
    CLIENT = "CLIENT"
    SESSION = "SESSION"


class ValidationStatus(StrEnum):
    OBSERVED = "OBSERVED"
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    CONTRADICTED = "CONTRADICTED"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"


class DetectionStatus(StrEnum):
    DETECTED = "DETECTED"
    INFERRED = "INFERRED"
    UNKNOWN = "UNKNOWN"


class SnapshotMode(StrEnum):
    FAST = "FAST"
    STANDARD = "STANDARD"
    DEEP = "DEEP"


class ProviderType(StrEnum):
    LOCAL = "LOCAL"
    OPENAI = "OPENAI"
    ANTHROPIC = "ANTHROPIC"
    GOOGLE = "GOOGLE"
    CUSTOM = "CUSTOM"


class ProviderStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DISABLED = "DISABLED"


class ModelProfileStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DISABLED = "DISABLED"


class ModelCapability(StrEnum):
    TEXT_GENERATION = "TEXT_GENERATION"
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    CODE_REASONING = "CODE_REASONING"
    CODE_GENERATION = "CODE_GENERATION"
    PLANNING = "PLANNING"
    SUMMARIZATION = "SUMMARIZATION"
    CLASSIFICATION = "CLASSIFICATION"
    LONG_CONTEXT = "LONG_CONTEXT"
    TOOL_USE = "TOOL_USE"
    HIGH_REASONING = "HIGH_REASONING"
    PRIVATE_INFERENCE = "PRIVATE_INFERENCE"


class PrivacyClass(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class CostClass(StrEnum):
    FREE = "FREE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    PREMIUM = "PREMIUM"


class LatencyClass(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ModelResponseStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ModelCostSource(StrEnum):
    REPORTED = "REPORTED"
    ESTIMATED = "ESTIMATED"
    UNKNOWN = "UNKNOWN"
