from enum import StrEnum


class ProjectStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class ProjectType(StrEnum):
    DFG_INTERNAL = "DFG_INTERNAL"
    CLIENT = "CLIENT"
    R_AND_D = "R_AND_D"


class RepositoryAdapterType(StrEnum):
    LOCAL_GIT = "LOCAL_GIT"


class RepositoryAccessMode(StrEnum):
    READ_ONLY = "READ_ONLY"


class AuthorityLevel(StrEnum):
    L0 = "L0"
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"


class TaskComplexity(StrEnum):
    T0 = "T0"
    T1 = "T1"
    T2 = "T2"
    T3 = "T3"
    T4 = "T4"


class TaskPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    BLOCKED = "BLOCKED"
    IMPLEMENTATION_COMPLETE = "IMPLEMENTATION_COMPLETE"
    DOCUMENTATION_PENDING = "DOCUMENTATION_PENDING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AcceptanceCriterionStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_EVALUATED = "NOT_EVALUATED"


class AllowedAction(StrEnum):
    READ_REPOSITORY = "READ_REPOSITORY"
    READ_DOCUMENTATION = "READ_DOCUMENTATION"
    RUN_TESTS = "RUN_TESTS"
    CREATE_TEMP_FILES = "CREATE_TEMP_FILES"
    WRITE_SOURCE = "WRITE_SOURCE"
    WRITE_TESTS = "WRITE_TESTS"
    WRITE_DOCUMENTATION = "WRITE_DOCUMENTATION"
    CREATE_MIGRATION = "CREATE_MIGRATION"
    CREATE_COMMIT = "CREATE_COMMIT"


class BlockerCode(StrEnum):
    MISSING_REPOSITORY = "MISSING_REPOSITORY"
    INVALID_CONTRACT = "INVALID_CONTRACT"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    AUTHORITY_INSUFFICIENT = "AUTHORITY_INSUFFICIENT"
    WORKSPACE_INVALID = "WORKSPACE_INVALID"
    REPOSITORY_STATE_UNSAFE = "REPOSITORY_STATE_UNSAFE"
    DECISION_REQUIRED = "DECISION_REQUIRED"
    DOCUMENTATION_REQUIRED = "DOCUMENTATION_REQUIRED"
    PROJECT_INACTIVE = "PROJECT_INACTIVE"


class TaskRunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class Actor(StrEnum):
    HUMAN = "HUMAN"
    CHATGPT = "CHATGPT"
    CODEX = "CODEX"
    LUCIUS = "LUCIUS"
    EXTERNAL_ENGINEERING_AGENT = "EXTERNAL_ENGINEERING_AGENT"
    SYSTEM = "SYSTEM"


class SourceType(StrEnum):
    CODE = "CODE"
    DOCUMENTATION = "DOCUMENTATION"
    TEST = "TEST"
    CONFIG = "CONFIG"
    GIT = "GIT"
    MEMORY = "MEMORY"
    EXTERNAL = "EXTERNAL"


class EvidenceStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    MISSING = "MISSING"


class RetrievalWarningCode(StrEnum):
    NO_RELEVANT_EVIDENCE = "NO_RELEVANT_EVIDENCE"
    CONTEXT_BUDGET_REACHED = "CONTEXT_BUDGET_REACHED"
    SOURCE_SKIPPED_BINARY = "SOURCE_SKIPPED_BINARY"
    SOURCE_SKIPPED_LARGE = "SOURCE_SKIPPED_LARGE"
    SOURCE_SKIPPED_SENSITIVE = "SOURCE_SKIPPED_SENSITIVE"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    SOURCE_MISSING = "SOURCE_MISSING"
    REPOSITORY_DIRTY = "REPOSITORY_DIRTY"


class MemoryType(StrEnum):
    SEMANTIC = "SEMANTIC"
    EPISODIC = "EPISODIC"
    PROCEDURAL = "PROCEDURAL"
    EVALUATIVE = "EVALUATIVE"
    PROJECT = "PROJECT"


class MemorySourceType(StrEnum):
    EVIDENCE_REFERENCE = "EVIDENCE_REFERENCE"
    TASK_RUN = "TASK_RUN"
    PROJECT_DOCUMENTATION = "PROJECT_DOCUMENTATION"
    AUDIT_EVENT = "AUDIT_EVENT"
    HUMAN_CORRECTION = "HUMAN_CORRECTION"
    FAILURE_EXPERIENCE = "FAILURE_EXPERIENCE"


class LearningCandidateType(StrEnum):
    PATTERN = "PATTERN"
    FAILURE_PATTERN = "FAILURE_PATTERN"
    PROCEDURE = "PROCEDURE"
    KNOWLEDGE_CORRECTION = "KNOWLEDGE_CORRECTION"
    OPTIMIZATION = "OPTIMIZATION"


class LearningCandidateStatus(StrEnum):
    PENDING = "PENDING"
    NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class KnowledgeFirewallClassification(StrEnum):
    PRIVATE = "PRIVATE"
    ABSTRACTABLE = "ABSTRACTABLE"
    GLOBAL_SAFE = "GLOBAL_SAFE"


class SanitizationStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    SANITIZED = "SANITIZED"
    REJECTED = "REJECTED"


class Environment(StrEnum):
    SANDBOX = "SANDBOX"
    DEVELOPMENT = "DEVELOPMENT"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"


class KnowledgeScope(StrEnum):
    GLOBAL = "GLOBAL"
    DFG = "DFG"
    DOMAIN = "DOMAIN"
    PROJECT = "PROJECT"
    CLIENT = "CLIENT"
    SESSION = "SESSION"


class ValidationStatus(StrEnum):
    OBSERVED = "OBSERVED"
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    CONTRADICTED = "CONTRADICTED"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"


class DetectionStatus(StrEnum):
    DETECTED = "DETECTED"
    INFERRED = "INFERRED"
    UNKNOWN = "UNKNOWN"


class SnapshotMode(StrEnum):
    FAST = "FAST"
    STANDARD = "STANDARD"
    DEEP = "DEEP"


class RepositoryStateClassification(StrEnum):
    CANONICAL_CLEAN = "CANONICAL_CLEAN"
    NON_CANONICAL_DIRTY = "NON_CANONICAL_DIRTY"
    NON_CANONICAL_HEAD_CHANGED = "NON_CANONICAL_HEAD_CHANGED"
    NON_CANONICAL_UNTRACKED_STATE = "NON_CANONICAL_UNTRACKED_STATE"
    NON_CANONICAL_EXTERNAL_MUTATION = "NON_CANONICAL_EXTERNAL_MUTATION"


class PlanningEvidenceMode(StrEnum):
    CURRENT_STATE_PLANNING = "CURRENT_STATE_PLANNING"
    HISTORICAL_STATE_PLANNING = "HISTORICAL_STATE_PLANNING"


class ProviderType(StrEnum):
    LOCAL = "LOCAL"
    OPENAI = "OPENAI"
    ANTHROPIC = "ANTHROPIC"
    GOOGLE = "GOOGLE"
    CUSTOM = "CUSTOM"


class ProviderStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DISABLED = "DISABLED"


class ModelProfileStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DISABLED = "DISABLED"


class ModelCapability(StrEnum):
    TEXT_GENERATION = "TEXT_GENERATION"
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    CODE_REASONING = "CODE_REASONING"
    CODE_GENERATION = "CODE_GENERATION"
    PLANNING = "PLANNING"
    SUMMARIZATION = "SUMMARIZATION"
    CLASSIFICATION = "CLASSIFICATION"
    LONG_CONTEXT = "LONG_CONTEXT"
    TOOL_USE = "TOOL_USE"
    HIGH_REASONING = "HIGH_REASONING"
    PRIVATE_INFERENCE = "PRIVATE_INFERENCE"


class PrivacyClass(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class CostClass(StrEnum):
    FREE = "FREE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    PREMIUM = "PREMIUM"


class LatencyClass(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ModelResponseStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ModelCostSource(StrEnum):
    REPORTED = "REPORTED"
    ESTIMATED = "ESTIMATED"
    UNKNOWN = "UNKNOWN"


class EngineeringPlanStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"


class PlanningBlockerCode(StrEnum):
    TASK_NOT_READY = "TASK_NOT_READY"
    TASK_CONTRACT_INVALID = "TASK_CONTRACT_INVALID"
    PROJECT_INACTIVE = "PROJECT_INACTIVE"
    REPOSITORY_SNAPSHOT_REQUIRED = "REPOSITORY_SNAPSHOT_REQUIRED"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    NO_RELEVANT_EVIDENCE = "NO_RELEVANT_EVIDENCE"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_POLICY_BLOCK = "MODEL_POLICY_BLOCK"
    PLANNING_CONTEXT_INVALID = "PLANNING_CONTEXT_INVALID"
    ENGINEERING_PLAN_INVALID = "ENGINEERING_PLAN_INVALID"
    AUTHORITY_ESCALATION_REQUIRED = "AUTHORITY_ESCALATION_REQUIRED"
    DECISION_REQUIRED = "DECISION_REQUIRED"


class PlanRiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PlanStepSupportStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    INFERRED = "INFERRED"
    BLOCKED_BY_UNKNOWN = "BLOCKED_BY_UNKNOWN"


class AcceptanceCoverageStatus(StrEnum):
    COVERED = "COVERED"
    PARTIALLY_COVERED = "PARTIALLY_COVERED"
    NOT_COVERED = "NOT_COVERED"
    BLOCKED = "BLOCKED"


class AffectedFileStatus(StrEnum):
    EXISTING_VERIFIED = "EXISTING_VERIFIED"
    LIKELY_EXISTING = "LIKELY_EXISTING"
    NEW_PROPOSED = "NEW_PROPOSED"
    UNKNOWN = "UNKNOWN"


class TestStrategyKind(StrEnum):
    STATIC = "STATIC"
    UNIT = "UNIT"
    INTEGRATION = "INTEGRATION"
    REGRESSION = "REGRESSION"
    SYSTEM = "SYSTEM"
    REAL_WORLD_VALIDATION = "REAL_WORLD_VALIDATION"


class ReplanReason(StrEnum):
    NEW_EVIDENCE = "NEW_EVIDENCE"
    TASK_CHANGED = "TASK_CHANGED"
    CONTRACT_CHANGED = "CONTRACT_CHANGED"
    PLAN_REJECTED = "PLAN_REJECTED"
    TEST_FAILURE = "TEST_FAILURE"
    HUMAN_FEEDBACK = "HUMAN_FEEDBACK"
    MODEL_FAILURE_RECOVERY = "MODEL_FAILURE_RECOVERY"


class EvaluationTargetType(StrEnum):
    RETRIEVAL = "RETRIEVAL"
    MEMORY = "MEMORY"
    PLANNER = "PLANNER"


class EvaluationRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"


class EvaluationCaseStatus(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    ERROR = "ERROR"


class EvaluationMetricName(StrEnum):
    EVIDENCE_PRECISION = "EVIDENCE_PRECISION"
    EVIDENCE_RECALL = "EVIDENCE_RECALL"
    AFFECTED_COMPONENT_PRECISION = "AFFECTED_COMPONENT_PRECISION"
    AFFECTED_COMPONENT_RECALL = "AFFECTED_COMPONENT_RECALL"
    AFFECTED_FILE_PRECISION = "AFFECTED_FILE_PRECISION"
    AFFECTED_FILE_RECALL = "AFFECTED_FILE_RECALL"
    ACCEPTANCE_COVERAGE = "ACCEPTANCE_COVERAGE"
    UNSUPPORTED_ASSUMPTION_RATE = "UNSUPPORTED_ASSUMPTION_RATE"
    HALLUCINATED_PATH_RATE = "HALLUCINATED_PATH_RATE"
    RISK_CORRECTNESS = "RISK_CORRECTNESS"
    AUTHORITY_CORRECTNESS = "AUTHORITY_CORRECTNESS"
    TEST_STRATEGY_COVERAGE = "TEST_STRATEGY_COVERAGE"
    DOCUMENTATION_COVERAGE = "DOCUMENTATION_COVERAGE"
    MEMORY_SCOPE_CORRECTNESS = "MEMORY_SCOPE_CORRECTNESS"
    MEMORY_CONFLICT_CORRECTNESS = "MEMORY_CONFLICT_CORRECTNESS"
    PRIVACY_BOUNDARY_CORRECTNESS = "PRIVACY_BOUNDARY_CORRECTNESS"
    PROVENANCE_COMPLETENESS = "PROVENANCE_COMPLETENESS"


class EvaluationHardGate(StrEnum):
    CLIENT_BOUNDARY_VIOLATION = "CLIENT_BOUNDARY_VIOLATION"
    PRIVACY_POLICY_VIOLATION = "PRIVACY_POLICY_VIOLATION"
    FABRICATED_EVIDENCE_REFERENCE = "FABRICATED_EVIDENCE_REFERENCE"
    CRITICAL_AUTHORITY_UNDERESTIMATION = "CRITICAL_AUTHORITY_UNDERESTIMATION"
    CRITICAL_RISK_UNDERESTIMATION = "CRITICAL_RISK_UNDERESTIMATION"
    REPOSITORY_REALITY_OVERRIDDEN_BY_MEMORY = "REPOSITORY_REALITY_OVERRIDDEN_BY_MEMORY"
    INVALID_PLAN_PROVENANCE = "INVALID_PLAN_PROVENANCE"


class EvaluationHardGateStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"


class EvaluationReleaseDecision(StrEnum):
    RELEASE_ELIGIBLE = "RELEASE_ELIGIBLE"
    RELEASE_WARNING = "RELEASE_WARNING"
    RELEASE_BLOCKED = "RELEASE_BLOCKED"


class EngineeringPlanEvaluationResult(StrEnum):
    PASS = "PASS"
    PASS_WITH_WARNINGS = "PASS_WITH_WARNINGS"
    FAIL = "FAIL"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class EngineeringPlanEvaluationMode(StrEnum):
    PLANNING_ONLY = "PLANNING_ONLY"
    PLAN_VS_IMPLEMENTATION = "PLAN_VS_IMPLEMENTATION"


class MetricApplicability(StrEnum):
    CAPTURED = "CAPTURED"
    NOT_CAPTURED = "NOT_CAPTURED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ImplementationChangeEvidenceState(StrEnum):
    CHANGE_CONFIRMED = "CHANGE_CONFIRMED"
    EXPECTED_CHANGE_MISSING = "EXPECTED_CHANGE_MISSING"
    NO_CHANGE_CONFIRMED = "NO_CHANGE_CONFIRMED"
    UNEXPECTED_CHANGE_DETECTED = "UNEXPECTED_CHANGE_DETECTED"
    NOT_CAPTURED = "NOT_CAPTURED"


class HumanRubricCaptureStatus(StrEnum):
    CAPTURED = "CAPTURED"
    NOT_CAPTURED = "NOT_CAPTURED"


class BenchmarkRunStatus(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    ERROR = "ERROR"
    NOT_RUN = "NOT_RUN"


class BenchmarkRegressionStatus(StrEnum):
    NO_REGRESSION = "NO_REGRESSION"
    REGRESSION = "REGRESSION"
    INCONCLUSIVE = "INCONCLUSIVE"
    NOT_RUN = "NOT_RUN"


class PilotLearningStatus(StrEnum):
    IDENTIFIED = "IDENTIFIED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    IMPLEMENTED = "IMPLEMENTED"


class RepositoryIntegrityResult(StrEnum):
    UNCHANGED = "UNCHANGED"
    HEAD_CHANGED = "HEAD_CHANGED"
    WORKTREE_CHANGED = "WORKTREE_CHANGED"
    NOT_CHECKED = "NOT_CHECKED"


class AutonomyRecommendation(StrEnum):
    NOT_READY_FOR_WRITE_AUTONOMY = "NOT_READY_FOR_WRITE_AUTONOMY"
    READY_FOR_LIMITED_WRITE_PILOT = "READY_FOR_LIMITED_WRITE_PILOT"
    READY_FOR_ANOTHER_LIMITED_WRITE_PILOT = "READY_FOR_ANOTHER_LIMITED_WRITE_PILOT"
    READY_FOR_BOUNDED_ENGINEERING_PILOT = "READY_FOR_BOUNDED_ENGINEERING_PILOT"
    NOT_READY_FOR_BOUNDED_ENGINEERING = "NOT_READY_FOR_BOUNDED_ENGINEERING"
    READY_FOR_ANOTHER_BOUNDED_ENGINEERING_PILOT = "READY_FOR_ANOTHER_BOUNDED_ENGINEERING_PILOT"
    READY_FOR_BOUNDED_MULTI_TASK_ENGINEERING = "READY_FOR_BOUNDED_MULTI_TASK_ENGINEERING"
    NOT_READY_FOR_BOUNDED_MULTI_TASK_ENGINEERING = "NOT_READY_FOR_BOUNDED_MULTI_TASK_ENGINEERING"
    READY_FOR_ANOTHER_BOUNDED_MULTI_TASK_ENGINEERING_PILOT = (
        "READY_FOR_ANOTHER_BOUNDED_MULTI_TASK_ENGINEERING_PILOT"
    )
    READY_FOR_SUPERVISED_ENGINEERING_WORKFLOW = "READY_FOR_SUPERVISED_ENGINEERING_WORKFLOW"
    NOT_READY_FOR_SUPERVISED_ENGINEERING_WORKFLOW = "NOT_READY_FOR_SUPERVISED_ENGINEERING_WORKFLOW"
    READY_FOR_ANOTHER_SUPERVISED_ENGINEERING_WORKFLOW = "READY_FOR_ANOTHER_SUPERVISED_ENGINEERING_WORKFLOW"
    READY_FOR_PERSISTENT_SUPERVISED_ENGINEERING = "READY_FOR_PERSISTENT_SUPERVISED_ENGINEERING"
    NOT_READY_FOR_PERSISTENT_SUPERVISED_ENGINEERING = "NOT_READY_FOR_PERSISTENT_SUPERVISED_ENGINEERING"
    READY_FOR_ANOTHER_PERSISTENT_SUPERVISED_WORKFLOW = "READY_FOR_ANOTHER_PERSISTENT_SUPERVISED_WORKFLOW"
    READY_FOR_NON_BLOCKING_PROJECT_QUEUE_PILOT = "READY_FOR_NON_BLOCKING_PROJECT_QUEUE_PILOT"
    NOT_READY_FOR_NON_BLOCKING_PROJECT_QUEUE = "NOT_READY_FOR_NON_BLOCKING_PROJECT_QUEUE"
    READY_FOR_ANOTHER_NON_BLOCKING_PROJECT_QUEUE_PILOT = "READY_FOR_ANOTHER_NON_BLOCKING_PROJECT_QUEUE_PILOT"
    READY_FOR_ANOTHER_CROSS_PROJECT_QUEUE_PILOT = "READY_FOR_ANOTHER_CROSS_PROJECT_QUEUE_PILOT"
    READY_FOR_MULTI_PROJECT_NON_BLOCKING_QUEUE = "READY_FOR_MULTI_PROJECT_NON_BLOCKING_QUEUE"
    READY_FOR_BOUNDED_WRITE_AUTONOMY = "READY_FOR_BOUNDED_WRITE_AUTONOMY"


class PersistentWorkflowState(StrEnum):
    OBJECTIVE_ACCEPTED = "OBJECTIVE_ACCEPTED"
    PLANNING = "PLANNING"
    PLAN_READY = "PLAN_READY"
    IMPLEMENTING = "IMPLEMENTING"
    VERIFYING = "VERIFYING"
    CHECKPOINT_REVIEW_REQUIRED = "CHECKPOINT_REVIEW_REQUIRED"
    PAUSED = "PAUSED"
    RESUME_VALIDATION = "RESUME_VALIDATION"
    BLOCKED = "BLOCKED"
    APPROVED_TO_CONTINUE = "APPROVED_TO_CONTINUE"
    COMPLETED_PENDING_INTEGRATION = "COMPLETED_PENDING_INTEGRATION"
    CLOSED = "CLOSED"


class ResumeValidationResult(StrEnum):
    SAFE_TO_RESUME = "SAFE_TO_RESUME"
    CHECKPOINT_REVIEW_REQUIRED = "CHECKPOINT_REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"


class QueueWorkItemState(StrEnum):
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_HUMAN = "WAITING_HUMAN"
    WAITING_EXTERNAL = "WAITING_EXTERNAL"
    BLOCKED_DEPENDENCY = "BLOCKED_DEPENDENCY"
    RETRY_LATER = "RETRY_LATER"
    READY_TO_RESUME = "READY_TO_RESUME"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
